# Generated by Django 3.2.11 on 2022-02-24 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_accomodation_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accomodation',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
