# Generated by Django 3.2.11 on 2022-03-21 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Highlights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sparkling_clean', models.BooleanField()),
                ('front_desk', models.BooleanField()),
                ('airport_transfer', models.BooleanField()),
                ('free_wifi', models.BooleanField()),
                ('sauna', models.BooleanField()),
            ],
        ),
    ]
