# Generated by Django 3.2.11 on 2022-03-28 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_guide'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('purpose', models.CharField(max_length=200)),
            ],
        ),
    ]
