# Generated by Django 3.2.11 on 2022-04-09 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_carbooking'),
    ]

    operations = [
        migrations.CreateModel(
            name='AirportTrasfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up', models.CharField(max_length=200)),
                ('drop_off', models.CharField(max_length=200)),
                ('no_of_travellers', models.IntegerField()),
                ('pick_up_date', models.DateField()),
                ('pck_up_time', models.CharField(max_length=100)),
            ],
        ),
    ]
