# Generated by Django 3.2.11 on 2022-04-10 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_airporttrasfer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='airporttrasfer',
            name='pick_up_date',
            field=models.CharField(max_length=200),
        ),
    ]
