# Generated by Django 3.2.11 on 2022-04-13 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_alter_airporttrasfer_pick_up_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('no_of_guests', models.IntegerField()),
            ],
        ),
    ]
