# Generated by Django 3.2.11 on 2022-04-13 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_accommodationbooking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationbooking',
            name='check_in',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='accommodationbooking',
            name='check_out',
            field=models.CharField(max_length=200),
        ),
    ]
