# Generated by Django 3.2.11 on 2022-04-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20220413_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Accommodation_name', models.CharField(max_length=200)),
                ('image1', models.ImageField(upload_to='images/')),
                ('image2', models.ImageField(upload_to='images/')),
                ('image3', models.ImageField(upload_to='images/')),
                ('image4', models.ImageField(upload_to='images/')),
                ('image5', models.ImageField(upload_to='images/')),
                ('image6', models.ImageField(upload_to='images/')),
                ('image7', models.ImageField(upload_to='images/')),
                ('latitude', models.DecimalField(decimal_places=15, max_digits=15)),
                ('longitude', models.DecimalField(decimal_places=15, max_digits=15)),
            ],
        ),
    ]
