# Generated by Django 3.2.11 on 2022-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_accommodationdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodationdetails',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='accommodationdetails',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
