# Generated by Django 3.2.11 on 2022-04-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20220414_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookingAccommodation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=200)),
                ('check_in', models.CharField(max_length=200)),
                ('check_out', models.CharField(max_length=200)),
                ('no_of_guests', models.IntegerField()),
                ('accommodation_name', models.CharField(max_length=200)),
            ],
        ),
    ]
